version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=ai_text_assistant
      - AI_API_KEY=${AI_API_KEY}
      - AI_API_ENDPOINT=${AI_API_ENDPOINT}
      - DEBUG=false
      - LOG_LEVEL=INFO
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=ai_text_assistant
    restart: unless-stopped

  background-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=ai_text_assistant
      - AI_API_KEY=${AI_API_KEY}
      - AI_API_ENDPOINT=${AI_API_ENDPOINT}
      - BACKGROUND_SERVICE_PORT=8001
    depends_on:
      - mongodb
    command: ["python", "run.py", "background", "--skip-setup"]
    restart: unless-stopped

volumes:
  mongodb_data: